
service: chatbot
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221


functions:
  getTemplateList:
    handler: handler.getTemplateList
  getTemplateContent:
    handler: handler.getTemplateContent
