export const apiEndPoints = {
    login: '/login',
    register: '/register',
    updateUser: '/update-user',
    forgot: '/forgot-pass?email=',
    validateRstPwdToken: '/validateRstPwdToken',
    changePwdAuth: '/change-password',
    validateToken: '/validate-token',
    workspaceCreate: '/workspace/create',
    workspaces: '/workspaces',
    searchWorkspace: '/searchWorkspaceOrTag?searchtxt=',
    updateWorkspace: '/updateWorkspaceById',
    User: '/user?email=',
    SortList: '/workspace/sort',
    logout: '/logout',
    getDocument: '/list-documents?id=',
    saveDocument: '/upload-document',
    getWorkspaceById: '/workspace-by-id?id=',
    getMergedDocuments: '/merged-documents?id=',
    mergeDocument: '/merge',
    saveMergeDocument: '/save-merged-document',
    editDocument: '/editDocument?id=',
    allWorkspacesDetails: '/list-workspaces',
    tags: '/tags',
    getDocumentDetails: '/document-details?id=',
    getMergeStatus: '/getMergeStatus?id=',
    sendMessage: '/message',
    getWorkspaceByWorkspaceName: '/getWorkspaceByWorkspaceName?workspaceName=',
    retrieveMessageByWorkspaceDocumentName:'/getMessages/workspaceNameBydocumentName?docName=',
    getUsers: '/users',
    shareWorkspace: '/workspace/share',
    allDocumentsDetails: '/documentDetails',
    sharedNotification:'/notification/shared',
    deleteDocument:'/delete-document',
    workspaceClone:'/workspace/clone',
    getDocumentMergeStatus: '/getDocumentMergeStatus?id=',
    updateWorkspaceMergeStatus: '/updateWorkspaceMergeStatus',
    inactiveExistingMerges: '/inactiveExistingMerges',
    resyncChanges: '/resyncChanges',
    getDocAnalytics:'/getDocAnalytics',
    saveDocAnalytics:'/saveDocAnalytics',
};
